### ISSUE TITLE
Messages do not persist when writing/receiving messages

### ISSUE THREAD

**Issue by JaceyPenny** [colin1006/Haskell-ANSI-IRC#1]
Hey Collin cool IRC, one thing I've noticed using Mac terminal (I booted up Linux and had the same issue): Whenever I send a message it always clears the screen before printing the next message, so I don't see any of the messages in a list. I haven't looked through the code at all but I'm sure it's an easy fix.

**Comment by cclemmons** [comment]
I'm not sure what was going on exactly. I use iTerm2 by default and had tuned it to that. I think that the Mac terminal shows \n differently, or at least how it handles \n when combined with ANSI scrolling codes is weird, but I just fixed it. Thanks
